
version: '3'

services:

  go:
    image: golang:1.17
    volumes:
      - ./:/app
# 以下两行 数据放在自定义目录
#      - /data/dcdb/fanhao/photos:/app/photos
#      - /data/dcdb/fanhao/fanhao.db:/app/fanhao.db
    ports: 
      - 8888:8888
    working_dir: /app
    environment:
      - GO111MODULE=on
      - GOPROXY=https://goproxy.cn,https://proxy.golang.org,direct
    command: "/app/fanhao"
    restart: always